#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if command -v ibus >/dev/null 2>&1; then
            ibus write-cache --system >/dev/null 2>&1 || true
        fi
        if command -v gtk-update-icon-cache >/dev/null 2>&1; then
            gtk-update-icon-cache -f /usr/share/icons/hicolor >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#
exit 0
